# Generated by Django 4.1.4 on 2023-06-20 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_question_created_at_remove_question_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 19, 37, 29, 295656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 19, 37, 29, 296116, tzinfo=datetime.timezone.utc)),
        ),
    ]
