# Generated by Django 4.1.4 on 2023-07-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_reply_question_question_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reply',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='web.reply'),
        ),
    ]
