# Generated by Django 4.1.4 on 2023-07-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_question_tags_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reply',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.reply'),
        ),
    ]
