# Generated by Django 4.1.4 on 2023-07-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_question_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='web.tag'),
        ),
    ]
