# Generated by Django 4.1.4 on 2023-07-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_remove_question_tags_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.question'),
        ),
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(default=None, null=True, to='web.question'),
        ),
    ]
