# Generated by Django 4.1.4 on 2023-07-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_remove_question_reply_remove_question_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
