# Generated by Django 4.1.4 on 2023-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_question_voters_reply_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='voters',
            new_name='voters_down',
        ),
        migrations.AddField(
            model_name='question',
            name='voters_up',
            field=models.TextField(default=[]),
        ),
    ]
