# Generated by Django 4.1.4 on 2023-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_rename_voters_reply_voters_down_reply_voters_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voters_down',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='voters_up',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reply',
            name='voters_down',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reply',
            name='voters_up',
            field=models.TextField(default=''),
        ),
    ]
